import type { Metadata } from "next";
import { Geist, Geist_Mono, Hepta_Slab } from "next/font/google";
import "./globals.css";
import MobileNavbar from "@/src/components/MobileNavbar";
import { Toaster } from 'sonner';
import { 
  IconAlertTriangle, IconCircleCheck, 
  IconCircleX, IconInfoCircle 
} from '@tabler/icons-react';
import Navbar from "@components/Navbar";
import VideoBackground from "@components/VideoBackground";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const heptaSlab = Hepta_Slab({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Andreea's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased overflow-x-hidden`}
    >
      <body className="min-h-full flex flex-col bg-[#141414] overflow-x-hidden">
        <VideoBackground />
        <MobileNavbar />
        <Navbar />
        {children}

        <Toaster
            icons={{
              success: <IconCircleCheck color='green' size={20} />,
              info: <IconInfoCircle color='blue' size={20} />,
              warning: <IconAlertTriangle color='#dbac02' size={20} />,
              error: <IconCircleX color='red' size={20} />,
            }}
            toastOptions={{
              style: {
                fontSize: '16px'
              }
            }}
          />
      </body>
    </html>
  );
}
